# Generated by Django 3.1.2 on 2020-10-21 18:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='exhibitionimages',
            options={'verbose_name': 'Фотография выставки', 'verbose_name_plural': 'Фотографии выставки'},
        ),
        migrations.AlterModelOptions(
            name='exhibitions',
            options={'verbose_name': 'Выставка', 'verbose_name_plural': 'Выставки'},
        ),
        migrations.AlterModelOptions(
            name='foreignnews',
            options={'verbose_name': 'Зарубежная новостa', 'verbose_name_plural': 'Зарубежные новости'},
        ),
        migrations.AlterModelOptions(
            name='mainslider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдеры'},
        ),
        migrations.AlterModelOptions(
            name='months',
            options={'verbose_name': 'Месяц', 'verbose_name_plural': 'Месяца'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='servicestypes',
            options={'verbose_name': 'Вид услуги', 'verbose_name_plural': 'Виды услуг'},
        ),
        migrations.RemoveField(
            model_name='services',
            name='service',
        ),
        migrations.AddField(
            model_name='services',
            name='service_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.servicestypes', verbose_name='Вид услуги'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activities',
            name='from_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='С какого'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='Название (анг.)'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='name_ru',
            field=models.CharField(max_length=255, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='name_tm',
            field=models.CharField(max_length=255, verbose_name='Название (туркм.)'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='organizers_en',
            field=models.CharField(max_length=255, verbose_name='Организаторы (анг.)'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='organizers_ru',
            field=models.CharField(max_length=255, verbose_name='Организаторы (рус.)'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='organizers_tm',
            field=models.CharField(max_length=255, verbose_name='Организаторы (туркм.)'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='place_en',
            field=models.CharField(max_length=128, verbose_name='Место провождения (анг.)'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='place_ru',
            field=models.CharField(max_length=128, verbose_name='Место провождения (рус.)'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='place_tm',
            field=models.CharField(max_length=128, verbose_name='Место провождения (туркм.)'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='to_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='По какое'),
        ),
        migrations.AlterField(
            model_name='exhibitionimages',
            name='exhibition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exhibitions', verbose_name='Выставка'),
        ),
        migrations.AlterField(
            model_name='exhibitionimages',
            name='image',
            field=models.ImageField(upload_to='exhibitions/images/', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='exhibitions',
            name='desc_en',
            field=models.TextField(verbose_name='Описание (анг.)'),
        ),
        migrations.AlterField(
            model_name='exhibitions',
            name='desc_ru',
            field=models.TextField(verbose_name='Описание (рус.)'),
        ),
        migrations.AlterField(
            model_name='exhibitions',
            name='desc_tm',
            field=models.TextField(verbose_name='Описание (туркм.)'),
        ),
        migrations.AlterField(
            model_name='exhibitions',
            name='main_image',
            field=models.ImageField(upload_to='exhibitions/main_images/', verbose_name='Главная фотография'),
        ),
        migrations.AlterField(
            model_name='exhibitions',
            name='slug',
            field=models.SlugField(verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='exhibitions',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name='Заголовок (анг.)'),
        ),
        migrations.AlterField(
            model_name='exhibitions',
            name='title_ru',
            field=models.CharField(max_length=255, verbose_name='Заголовок (рус.)'),
        ),
        migrations.AlterField(
            model_name='exhibitions',
            name='title_tm',
            field=models.CharField(max_length=255, verbose_name='Заголовок (туркм.)'),
        ),
        migrations.AlterField(
            model_name='foreignnews',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата опубликования'),
        ),
        migrations.AlterField(
            model_name='foreignnews',
            name='desc_en',
            field=models.TextField(verbose_name='Описание (анг.)'),
        ),
        migrations.AlterField(
            model_name='foreignnews',
            name='desc_ru',
            field=models.TextField(verbose_name='Описание (рус.)'),
        ),
        migrations.AlterField(
            model_name='foreignnews',
            name='desc_tm',
            field=models.TextField(verbose_name='Описание (туркм.)'),
        ),
        migrations.AlterField(
            model_name='foreignnews',
            name='image',
            field=models.ImageField(upload_to='news/', verbose_name='Главная картинка'),
        ),
        migrations.AlterField(
            model_name='foreignnews',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.months', verbose_name='Месяц опубликования'),
        ),
        migrations.AlterField(
            model_name='foreignnews',
            name='title_en',
            field=models.CharField(max_length=128, verbose_name='Заголовок (анг.)'),
        ),
        migrations.AlterField(
            model_name='foreignnews',
            name='title_ru',
            field=models.CharField(max_length=128, verbose_name='Заголовок (рус.)'),
        ),
        migrations.AlterField(
            model_name='foreignnews',
            name='title_tm',
            field=models.CharField(max_length=128, verbose_name='Заголовок (туркм.)'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='image',
            field=models.ImageField(upload_to='slider/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='title_en',
            field=models.CharField(max_length=128, verbose_name='Название (анг.)'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='title_ru',
            field=models.CharField(max_length=128, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='title_tm',
            field=models.CharField(max_length=128, verbose_name='Название (туркм.)'),
        ),
        migrations.AlterField(
            model_name='months',
            name='name_en',
            field=models.CharField(max_length=12, verbose_name='Название (анг.)'),
        ),
        migrations.AlterField(
            model_name='months',
            name='name_ru',
            field=models.CharField(max_length=12, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='months',
            name='name_tm',
            field=models.CharField(max_length=12, verbose_name='Название (туркм.)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата опубликования'),
        ),
        migrations.AlterField(
            model_name='news',
            name='desc_en',
            field=models.TextField(verbose_name='Описание (анг.)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='desc_ru',
            field=models.TextField(verbose_name='Описание (рус.)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='desc_tm',
            field=models.TextField(verbose_name='Описание (туркм.)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/', verbose_name='Главная картинка'),
        ),
        migrations.AlterField(
            model_name='news',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.months', verbose_name='Месяц опубликования'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=128, verbose_name='Заголовок (анг.)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=128, verbose_name='Заголовок (рус.)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_tm',
            field=models.CharField(max_length=128, verbose_name='Заголовок (туркм.)'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='image',
            field=models.ImageField(upload_to='partners/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='name_en',
            field=models.CharField(max_length=32, verbose_name='Название (анг.)'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='name_ru',
            field=models.CharField(max_length=32, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='name_tm',
            field=models.CharField(max_length=32, verbose_name='Название (туркм.)'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='slug',
            field=models.SlugField(verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name_en',
            field=models.CharField(max_length=64, verbose_name='Название (анг.)'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name_ru',
            field=models.CharField(max_length=64, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name_tm',
            field=models.CharField(max_length=64, verbose_name='Название (туркм.)'),
        ),
        migrations.AlterField(
            model_name='servicestypes',
            name='name_en',
            field=models.CharField(max_length=64, verbose_name='Название (анг.)'),
        ),
        migrations.AlterField(
            model_name='servicestypes',
            name='name_ru',
            field=models.CharField(max_length=64, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='servicestypes',
            name='name_tm',
            field=models.CharField(max_length=64, verbose_name='Название (туркм.)'),
        ),
    ]
