# Generated by Django 3.1.2 on 2020-10-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201021_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainslider',
            name='title_en',
            field=models.CharField(blank=True, max_length=128, verbose_name='Название (анг.)'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='title_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='title_tm',
            field=models.CharField(blank=True, max_length=128, verbose_name='Название (туркм.)'),
        ),
    ]
