# Generated by Django 3.1.2 on 2020-10-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mainslider_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainslider',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=0,verbose_name='Последовательность'),
        ),
    ]
