# Generated by Django 3.1.2 on 2020-10-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201022_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainslider',
            name='ordering',
            field=models.PositiveSmallIntegerField(verbose_name='Последовательность'),
        ),
    ]
