# Generated by Django 3.1.2 on 2020-10-21 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201022_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainslider',
            name='ordering',
        ),
    ]
