# Generated by Django 3.1.2 on 2020-10-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_mainslider_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainslider',
            name='ordering',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Последовательность'),
        ),
    ]
