# Generated by Django 3.1.2 on 2020-10-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name='Заголовок (анг.)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, verbose_name='Заголовок (рус.)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_tm',
            field=models.CharField(max_length=255, verbose_name='Заголовок (туркм.)'),
        ),
    ]
