# Generated by Django 3.1.2 on 2020-10-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201022_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitions',
            name='installer',
            field=models.CharField(max_length=255, null=True, verbose_name='Установщик'),
        ),
    ]
