# Generated by Django 3.1.2 on 2020-10-22 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201022_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitions',
            name='from_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='С (дата)'),
        ),
        migrations.AlterField(
            model_name='exhibitions',
            name='to_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='До (дата)'),
        ),
    ]
