# Generated by Django 3.1.2 on 2020-10-22 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_quotes_virtualexpoimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quotes',
        ),
    ]
