# Generated by Django 3.1.2 on 2020-10-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_quotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualexpoimages',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Последовательность'),
        ),
    ]
