# Generated by Django 3.1.2 on 2020-10-22 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20201023_0114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VirtualExpoImages',
        ),
    ]
