# Generated by Django 3.1.2 on 2020-10-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_delete_virtualexpoimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualExpoImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='virtualexpo/', verbose_name='Картинка')),
                ('ordering', models.PositiveSmallIntegerField(default=1, verbose_name='Последовательность')),
            ],
            options={
                'verbose_name': 'Картинка виртуальной экскурсии',
                'verbose_name_plural': 'Картинки виртуальной экскурсии',
            },
        ),
    ]
