# Generated by Django 3.1.2 on 2020-10-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_virtualexpoimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualexpoimages',
            name='ordering',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Последовательность'),
        ),
    ]
