# Generated by Django 3.1.2 on 2020-10-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20201023_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignExhibitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='foreign_exhibitions/', verbose_name='')),
                ('name_tm', models.CharField(max_length=255, verbose_name='Название (туркм.)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (рус.)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Название (анг.)')),
                ('desc_tm', models.TextField(verbose_name='Описание (туркм.)')),
                ('desc_ru', models.TextField(verbose_name='Описание (рус.)')),
                ('desc_en', models.TextField(verbose_name='Описание (анг.)')),
            ],
            options={
                'verbose_name': 'Зарубежные выставки',
                'verbose_name_plural': 'Зарубежные выставки',
            },
        ),
        migrations.DeleteModel(
            name='Activities',
        ),
    ]
