# Generated by Django 3.1.2 on 2020-10-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_foreignexhibitions_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partners',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='name_tm',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='slug',
        ),
        migrations.AlterField(
            model_name='foreignexhibitions',
            name='main_image',
            field=models.ImageField(upload_to='foreign_exhibitions/', verbose_name='Главная картинка'),
        ),
    ]
