# Generated by Django 3.1.2 on 2020-10-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20201023_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=128, verbose_name='Телефон')),
                ('faks', models.CharField(max_length=128, verbose_name='Факс')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('email1', models.EmailField(max_length=254, verbose_name='Электронная почта 1')),
                ('email2', models.EmailField(max_length=254, verbose_name='Электронная почта 2')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
