# Generated by Django 3.1.2 on 2020-10-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_questionanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='question',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='answer_en',
            field=models.TextField(default='', verbose_name='Ответы (анг.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='answer_ru',
            field=models.TextField(default=1, verbose_name='Ответы (рус.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='answer_tm',
            field=models.TextField(default=1, verbose_name='Ответы (туркм.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='question_en',
            field=models.CharField(default=1, max_length=255, verbose_name='Вопросы (анг.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='question_ru',
            field=models.CharField(default=1, max_length=255, verbose_name='Вопросы (рус.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='question_tm',
            field=models.CharField(default=1, max_length=255, verbose_name='Вопросы (туркм.)'),
            preserve_default=False,
        ),
    ]
