# Generated by Django 3.1.2 on 2020-10-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20201024_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='TppAdvantages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantage_tm', models.TextField(verbose_name='Преимущества (туркм.)')),
                ('advantage_ru', models.TextField(verbose_name='Преимущества (рус.)')),
                ('advantage_en', models.TextField(verbose_name='Преимущества (анг.)')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
    ]
