# Generated by Django 3.1.2 on 2020-10-27 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20201028_0140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Benefits',
        ),
    ]
