# Generated by Django 3.1.2 on 2020-10-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_delete_benefits'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TppAdvantages',
        ),
    ]
