# Generated by Django 3.1.2 on 2020-10-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_delete_tppadvantages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='Название (анг.)'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='name_ru',
            field=models.CharField(max_length=255, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='name_tm',
            field=models.CharField(max_length=255, verbose_name='Название (туркм.)'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='place_en',
            field=models.CharField(max_length=255, verbose_name='Место провождения (анг.)'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='place_ru',
            field=models.CharField(max_length=255, verbose_name='Место провождения (рус.)'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='place_tm',
            field=models.CharField(max_length=255, verbose_name='Место провождения (туркм.)'),
        ),
        migrations.AlterField(
            model_name='exhibitions',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name='Заголовок (анг.)'),
        ),
        migrations.AlterField(
            model_name='exhibitions',
            name='title_ru',
            field=models.CharField(max_length=255, verbose_name='Заголовок (рус.)'),
        ),
        migrations.AlterField(
            model_name='exhibitions',
            name='title_tm',
            field=models.CharField(max_length=255, verbose_name='Заголовок (туркм.)'),
        ),
        migrations.AlterField(
            model_name='foreignexhibitions',
            name='slug',
            field=models.SlugField(verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='title_ru',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='title_tm',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name='Заголовок (анг.)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, verbose_name='Заголовок (рус.)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_tm',
            field=models.CharField(max_length=255, verbose_name='Заголовок (туркм.)'),
        ),
        migrations.AlterField(
            model_name='servicestypes',
            name='name_en',
            field=models.CharField(max_length=128, verbose_name='Название (анг.)'),
        ),
        migrations.AlterField(
            model_name='servicestypes',
            name='name_ru',
            field=models.CharField(max_length=128, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='servicestypes',
            name='name_tm',
            field=models.CharField(max_length=128, verbose_name='Название (туркм.)'),
        ),
    ]
