# Generated by Django 3.1.2 on 2020-10-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20201028_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainslider',
            name='image',
            field=models.ImageField(upload_to='slider/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (анг.)'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='title_tm',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (туркм.)'),
        ),
    ]
