# Generated by Django 3.1.2 on 2020-10-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20201028_0332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='Activities',
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.RemoveField(
            model_name='exhibitionimages',
            name='exhibition',
        ),
        migrations.DeleteModel(
            name='ForeignExhibitions',
        ),
        migrations.RemoveField(
            model_name='news',
            name='month',
        ),
        migrations.DeleteModel(
            name='Partners',
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
        migrations.DeleteModel(
            name='Quotes',
        ),
        migrations.DeleteModel(
            name='ServicesTypes',
        ),
        migrations.DeleteModel(
            name='VirtualExpoImages',
        ),
        migrations.DeleteModel(
            name='ExhibitionImages',
        ),
        migrations.DeleteModel(
            name='Exhibitions',
        ),
        migrations.DeleteModel(
            name='Months',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
