# Generated by Django 3.1.2 on 2020-10-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tm', models.CharField(blank=True, max_length=255, verbose_name='Название (туркм.)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Название (рус.)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Название (анг.)')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='Картинка')),
                ('ordering', models.PositiveSmallIntegerField(default=1, verbose_name='Последовательность')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
    ]
