# Generated by Django 3.1.2 on 2020-10-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tm', models.CharField(max_length=12, verbose_name='Название (туркм.)')),
                ('name_ru', models.CharField(max_length=12, verbose_name='Название (рус.)')),
                ('name_en', models.CharField(max_length=12, verbose_name='Название (анг.)')),
            ],
            options={
                'verbose_name': 'Месяц',
                'verbose_name_plural': 'Месяца',
            },
        ),
    ]
