# Generated by Django 3.1.2 on 2020-10-28 17:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tm', models.CharField(max_length=255, verbose_name='Заголовок (туркм.)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (рус.)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок (анг.)')),
                ('desc_tm', models.TextField(verbose_name='Описание (туркм.)')),
                ('desc_ru', models.TextField(verbose_name='Описание (рус.)')),
                ('desc_en', models.TextField(verbose_name='Описание (анг.)')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Главная картинка')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Дата опубликования')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.months', verbose_name='Месяц опубликования')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
