# Generated by Django 3.1.2 on 2020-10-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_aboutus_activities_benefits_contacts_exhibitionimages_exhibitions_partners_questionanswer_quotes_ser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignExhibitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='foreign_exhibitions/', verbose_name='')),
                ('name_tm', models.CharField(max_length=255, verbose_name='Название (туркм.)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (рус.)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Название (анг.)')),
                ('desc_tm', models.TextField(verbose_name='Описание (туркм.)')),
                ('desc_ru', models.TextField(verbose_name='Описание (рус.)')),
                ('desc_en', models.TextField(verbose_name='Описание (анг.)')),
                ('slug', models.SlugField(default='', verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Зарубежная выставка',
                'verbose_name_plural': 'Зарубежные выставки',
            },
        ),
        migrations.CreateModel(
            name='TppAdvantages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantage_tm', models.TextField(verbose_name='Преимущества (туркм.)')),
                ('advantage_ru', models.TextField(verbose_name='Преимущества (рус.)')),
                ('advantage_en', models.TextField(verbose_name='Преимущества (анг.)')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
    ]
