# Generated by Django 3.1.2 on 2020-10-28 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_foreignexhibitions_tppadvantages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TppAdvantages',
        ),
    ]
