# Generated by Django 3.1.2 on 2020-10-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_tppadvantages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefits',
            name='desc_en',
            field=models.TextField(verbose_name='Преимущ'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='desc_ru',
            field=models.TextField(verbose_name='Преимущ'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='desc_tm',
            field=models.TextField(verbose_name='Преимущ'),
        ),
    ]
