# Generated by Django 3.1.2 on 2020-10-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201029_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tm', models.CharField(max_length=255, verbose_name='Название (туркм.)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (рус.)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Название (анг.)')),
                ('desc_tm', models.TextField(verbose_name='Описание (туркм.)')),
                ('desc_ru', models.TextField(verbose_name='Описание (рус.)')),
                ('desc_en', models.TextField(verbose_name='Описание (анг.)')),
                ('from_date', models.DateField(verbose_name='С какого')),
                ('to_date', models.DateField(verbose_name='По какое')),
                ('organizers_tm', models.CharField(max_length=255, verbose_name='Организаторы (туркм.)')),
                ('organizers_ru', models.CharField(max_length=255, verbose_name='Организаторы (рус.)')),
                ('organizers_en', models.CharField(max_length=255, verbose_name='Организаторы (анг.)')),
            ],
            options={
                'verbose_name': 'Тендер',
                'verbose_name_plural': 'Тендеры',
            },
        ),
    ]
