# Generated by Django 3.1.2 on 2020-10-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tenders'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenders',
            name='main_image',
            field=models.ImageField(default=1, upload_to='tenders/', verbose_name='Главная картинка'),
            preserve_default=False,
        ),
    ]
