# Generated by Django 3.1.2 on 2020-10-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201029_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitions',
            name='installer',
        ),
        migrations.AddField(
            model_name='exhibitions',
            name='installer_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Установщик (анг.)'),
        ),
        migrations.AddField(
            model_name='exhibitions',
            name='installer_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Установщик (рус.)'),
        ),
        migrations.AddField(
            model_name='exhibitions',
            name='installer_tk',
            field=models.CharField(max_length=255, null=True, verbose_name='Установщик (туркм.)'),
        ),
    ]
