# Generated by Django 3.1.2 on 2020-10-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201029_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='months',
            name='name_en',
            field=models.CharField(max_length=32, verbose_name='Название (анг.)'),
        ),
        migrations.AlterField(
            model_name='months',
            name='name_ru',
            field=models.CharField(max_length=32, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='months',
            name='name_tk',
            field=models.CharField(max_length=32, verbose_name='Название (туркм.)'),
        ),
    ]
