# Generated by Django 3.1.2 on 2020-10-29 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201029_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignexhibitions',
            name='from_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='С какого'),
        ),
        migrations.AddField(
            model_name='foreignexhibitions',
            name='to_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='По какое'),
        ),
        migrations.AlterField(
            model_name='exhibitions',
            name='installer_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Организаторы (анг.)'),
        ),
        migrations.AlterField(
            model_name='exhibitions',
            name='installer_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Организаторы (рус.)'),
        ),
        migrations.AlterField(
            model_name='exhibitions',
            name='installer_tk',
            field=models.CharField(max_length=255, null=True, verbose_name='Организаторы (туркм.)'),
        ),
    ]
