# Generated by Django 3.1.2 on 2020-10-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201030_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='TppBranches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tk', models.CharField(max_length=255, verbose_name='Название (туркм.)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (рус.)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Название (анг.)')),
                ('address_tk', models.CharField(max_length=255, verbose_name='Адрес (туркм.)')),
                ('address_ru', models.CharField(max_length=255, verbose_name='Адрес (рус.)')),
                ('address_en', models.CharField(max_length=255, verbose_name='Адрес (анг.)')),
                ('desc_tk', models.TextField(verbose_name='Описание (туркм.)')),
                ('desc_ru', models.TextField(verbose_name='Описание (рус.)')),
                ('desc_en', models.TextField(verbose_name='Описание (анг.)')),
                ('phone', models.CharField(max_length=16, verbose_name='Тел.')),
                ('fax', models.CharField(max_length=16, verbose_name='Факс')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Подразделение ТПП',
                'verbose_name_plural': 'Подразделения ТПП',
            },
        ),
    ]
