# Generated by Django 3.1.2 on 2020-10-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_tppbranches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tppbranches',
            name='fax',
            field=models.CharField(max_length=32, verbose_name='Факс'),
        ),
        migrations.AlterField(
            model_name='tppbranches',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='Тел.'),
        ),
    ]
