# Generated by Django 3.1.2 on 2020-10-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_reklambanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='address',
        ),
        migrations.AddField(
            model_name='contacts',
            name='address_en',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес (анг.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='address_ru',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес (рус.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='address_tk',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес (туркм.)'),
            preserve_default=False,
        ),
    ]
