# Generated by Django 3.1.2 on 2020-10-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20201031_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='email1',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='email2',
        ),
        migrations.AddField(
            model_name='contacts',
            name='website',
            field=models.EmailField(default='', max_length=254, verbose_name='Веб сайт'),
            preserve_default=False,
        ),
    ]
