# Generated by Django 3.1.2 on 2020-10-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20201031_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='website',
            field=models.CharField(max_length=254, verbose_name='Веб сайт'),
        ),
    ]
