# Generated by Django 3.1.2 on 2020-10-30 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20201031_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenders',
            name='main_image',
        ),
    ]
