# Generated by Django 3.1.2 on 2020-10-30 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_tenders_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenders',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='tenders',
            name='to_date',
        ),
        migrations.AddField(
            model_name='tenders',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Kакого'),
        ),
    ]
