# Generated by Django 3.1.2 on 2020-11-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20201031_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainslider',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mainslider',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='mainslider',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='mainslider',
            name='title_tk',
        ),
        migrations.AddField(
            model_name='mainslider',
            name='image_en',
            field=models.ImageField(default='', upload_to='slider/', verbose_name='Картинка (анг.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainslider',
            name='image_ru',
            field=models.ImageField(default='', upload_to='slider/', verbose_name='Картинка (рус.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainslider',
            name='image_tk',
            field=models.ImageField(default='', upload_to='slider/', verbose_name='Картинка (туркм.)'),
            preserve_default=False,
        ),
    ]
