# Generated by Django 3.1.2 on 2020-11-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20201106_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reklambanner',
            name='image',
        ),
        migrations.AddField(
            model_name='reklambanner',
            name='image_en',
            field=models.ImageField(default='', upload_to='banners/', verbose_name='Картинка (анг.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reklambanner',
            name='image_ru',
            field=models.ImageField(default='', upload_to='banners/', verbose_name='Картинка (рус.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reklambanner',
            name='image_tk',
            field=models.ImageField(default='', upload_to='banners/', verbose_name='Картинка (туркм.)'),
            preserve_default=False,
        ),
    ]
