# Generated by Django 3.1.2 on 2020-11-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20201107_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipjoining',
            name='anketa_en',
            field=models.FileField(default='', upload_to='membership_application/', verbose_name='Анкета (анг.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershipjoining',
            name='anketa_ru',
            field=models.FileField(default='', upload_to='membership_application/', verbose_name='Анкета (рус.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershipjoining',
            name='anketa_tk',
            field=models.FileField(default='', upload_to='membership_application/', verbose_name='Анкета (туркм.)'),
            preserve_default=False,
        ),
    ]
