# Generated by Django 3.1.2 on 2020-11-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20201107_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tk', models.CharField(max_length=255, verbose_name='Название (туркм.)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (рус.)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Название (анг.)')),
                ('address_tk', models.CharField(max_length=255, verbose_name='Адрес (туркм.)')),
                ('address_ru', models.CharField(max_length=255, verbose_name='Адрес (рус.)')),
                ('address_en', models.CharField(max_length=255, verbose_name='Адрес (анг.)')),
                ('phone', models.CharField(max_length=128, verbose_name='Телефон')),
                ('faks', models.CharField(max_length=128, verbose_name='Факс')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('website', models.CharField(max_length=254, verbose_name='Веб сайт')),
                ('activity_tk', models.CharField(max_length=255, verbose_name='Сфера деятельности (туркм.)')),
                ('activity_ru', models.CharField(max_length=255, verbose_name='Сфера деятельности (рус.)')),
                ('activity_en', models.CharField(max_length=255, verbose_name='Сфера деятельности (анг.)')),
                ('logo', models.ImageField(upload_to='partners_registry/', verbose_name='Логотип (туркм.)')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Реестр партнеров',
            },
        ),
    ]
