# Generated by Django 3.1.2 on 2020-11-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_partnersregistry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnersregistry',
            name='logo',
            field=models.ImageField(upload_to='partners_registry/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='partnersregistry',
            name='website',
            field=models.CharField(blank=True, max_length=254, verbose_name='Веб сайт'),
        ),
    ]
