# Generated by Django 3.1.2 on 2020-11-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitions',
            name='desc_en',
            field=models.TextField(blank=True, verbose_name='Описание (анг.)'),
        ),
        migrations.AlterField(
            model_name='exhibitions',
            name='desc_ru',
            field=models.TextField(blank=True, verbose_name='Описание (рус.)'),
        ),
        migrations.AlterField(
            model_name='exhibitions',
            name='desc_tk',
            field=models.TextField(blank=True, verbose_name='Описание (туркм.)'),
        ),
    ]
