# Generated by Django 3.1.2 on 2020-11-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20201109_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitions',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='exhibitions/main_images/', verbose_name='Главная фотография'),
        ),
    ]
