# Generated by Django 3.1.2 on 2020-11-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20201109_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreigncommercialoffers',
            name='country_en',
            field=models.CharField(max_length=255, verbose_name='Страна (анг.)'),
        ),
        migrations.AlterField(
            model_name='foreigncommercialoffers',
            name='country_ru',
            field=models.CharField(max_length=255, verbose_name='Страна (рус.)'),
        ),
        migrations.AlterField(
            model_name='foreigncommercialoffers',
            name='country_tk',
            field=models.CharField(max_length=255, verbose_name='Страна (туркм.)'),
        ),
    ]
