# Generated by Django 3.1.2 on 2020-11-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20201109_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcipantEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_tk', models.TextField(verbose_name='Описание (туркм.)')),
                ('desc_ru', models.TextField(verbose_name='Описание (рус.)')),
                ('desc_en', models.TextField(verbose_name='Описание (анг.)')),
            ],
            options={
                'verbose_name': 'Участнику мероприятия',
                'verbose_name_plural': 'Участникам мероприятий',
            },
        ),
    ]
