# Generated by Django 3.1.2 on 2020-11-10 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_parcipantevents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foreignexhibitions',
            name='main_image',
        ),
    ]
