# Generated by Django 3.1.2 on 2020-11-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_remove_foreignexhibitions_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitions',
            name='main_image',
        ),
    ]
