# Generated by Django 3.1.2 on 2020-11-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_remove_exhibitions_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPPInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('address_tk', models.CharField(max_length=255, verbose_name='Адрес (туркм.)')),
                ('address_ru', models.CharField(max_length=255, verbose_name='Адрес (рус.)')),
                ('address_en', models.CharField(max_length=255, verbose_name='Адрес (анг.)')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информации',
            },
        ),
    ]
