# Generated by Django 3.1.2 on 2020-11-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_foreignexhibitions_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foreignexhibitions',
            name='main_image',
        ),
    ]
