# Generated by Django 3.1.2 on 2020-11-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressToPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_tk', models.TextField(verbose_name='Описание (туркм.)')),
                ('desc_ru', models.TextField(verbose_name='Описание (рус.)')),
                ('desc_en', models.TextField(verbose_name='Описание (анг.)')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращение',
            },
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Картинка', 'verbose_name_plural': 'Галерея'},
        ),
    ]
